let RGB: neopixel.Strip = null
input.onButtonPressed(Button.A, function () {
    for (let index = 0; index < 2; index++) {
        maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 100)
        maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 100)
        RGB = neopixel.create(DigitalPin.P15, 1, NeoPixelMode.RGB)
        RGB.showColor(neopixel.colors(NeoPixelColors.Red))
        music.playTone(659, music.beat(BeatFraction.Eighth))
        basic.pause(500)
        RGB = neopixel.create(DigitalPin.P15, 2, NeoPixelMode.RGB)
        RGB.showColor(neopixel.colors(NeoPixelColors.Red))
        music.playTone(698, music.beat(BeatFraction.Eighth))
        basic.pause(500)
        RGB = neopixel.create(DigitalPin.P15, 3, NeoPixelMode.RGB)
        RGB.showColor(neopixel.colors(NeoPixelColors.Red))
        music.playTone(784, music.beat(BeatFraction.Eighth))
        basic.pause(500)
        RGB = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)
        RGB.showColor(neopixel.colors(NeoPixelColors.Red))
        music.playTone(880, music.beat(BeatFraction.Eighth))
        basic.pause(500)
        RGB = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)
        RGB.showColor(neopixel.colors(NeoPixelColors.Black))
        music.playTone(988, music.beat(BeatFraction.Eighth))
        basic.pause(500)
    }
    for (let index = 0; index < 2; index++) {
        maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 100)
        maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 100)
        RGB = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)
        RGB.showColor(neopixel.colors(NeoPixelColors.Green))
        music.playTone(131, music.beat(BeatFraction.Eighth))
        basic.pause(500)
        RGB.showColor(neopixel.colors(NeoPixelColors.Black))
        RGB = neopixel.create(DigitalPin.P15, 3, NeoPixelMode.RGB)
        RGB.showColor(neopixel.colors(NeoPixelColors.Green))
        music.playTone(147, music.beat(BeatFraction.Eighth))
        basic.pause(500)
        RGB.showColor(neopixel.colors(NeoPixelColors.Black))
        RGB = neopixel.create(DigitalPin.P15, 2, NeoPixelMode.RGB)
        RGB.showColor(neopixel.colors(NeoPixelColors.Green))
        music.playTone(165, music.beat(BeatFraction.Eighth))
        basic.pause(500)
        RGB.showColor(neopixel.colors(NeoPixelColors.Black))
        RGB = neopixel.create(DigitalPin.P15, 1, NeoPixelMode.RGB)
        RGB.showColor(neopixel.colors(NeoPixelColors.Green))
        music.playTone(175, music.beat(BeatFraction.Eighth))
        basic.pause(500)
        RGB.showColor(neopixel.colors(NeoPixelColors.Black))
        RGB = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)
        RGB.showColor(neopixel.colors(NeoPixelColors.Black))
        music.playTone(196, music.beat(BeatFraction.Eighth))
        basic.pause(500)
    }
    maqueen.motorStop(maqueen.Motors.All)
})
